# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
name: Multi-Platform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OS Information
        run: |
          echo "Running on Ubuntu Linux"
          uname -a

      - name: Create and Display File
        run: |
          echo "Hello from the Linux runner!" 
          cat linux_test.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OS Information
        run: |
          echo "Running on Windows Server"
          systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

      - name: Create and Display File
        run: |
          echo "Hello from the Windows runner!" > windows_test.txt
          type windows_test.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OS Information
        run: |
          echo "Running on macOS"
          uname -a

      - name: Create and Display File
        run: |
          echo "Hello from the Mac runner!" > mac_test.txt
          cat mac_test.txt
