# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Multiplatform flow
on: push

jobs:
  ubuntu-job:
    name: Ubuntu Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: OS Info
        run: uname -a
      - name: Create and Show File
        run: |
          echo "Hello from Ubuntu" > info.txt
          cat info.txt

  windows-job:
    name: Windows Job
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: OS Info
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
      - name: Create and Show File
        run: |
          echo "Hello from Windows " > info.txt
          type info.txt

  macos-job:
    name: macOS Job
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: OS Info
        run: sw_vers
      - name: Create and Show File
        run: |
          echo "Hello from macOS" > info.txt
          cat info.txt
